; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = +<*> -<simulator/>

[env:simulator1]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = -<*> +<simulator/sim1/>

[env:simulator2]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = -<*> +<simulator/sim2/>

[env:simulator3]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = -<*> +<simulator/sim3/>